IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'WOAdmin')
CREATE LOGIN [WOAdmin] WITH PASSWORD = 'p@ssw0rd'
GO
CREATE USER [WOAdmin] FOR LOGIN [WOAdmin]
GO
GRANT DELETE TO [WOAdmin]
GRANT EXECUTE TO [WOAdmin]
GRANT INSERT TO [WOAdmin]
GRANT REFERENCES TO [WOAdmin]
GRANT SELECT TO [WOAdmin]
GRANT UPDATE TO [WOAdmin]
