CREATE TABLE [dbo].[Items_Weapons]
(
[ItemID] [int] NOT NULL IDENTITY(101001, 1),
[FNAME] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Items_Wea__FNAME__2F2FFC0C] DEFAULT ('ITEM000'),
[Category] [int] NOT NULL CONSTRAINT [DF__Items_Wea__Categ__30242045] DEFAULT ((0)),
[Name] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Items_Weapons_Name] DEFAULT (N'Name'),
[Description] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Items_Weapons_Description] DEFAULT (N'Description'),
[MuzzleOffset] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Items_Weapons_Offset] DEFAULT ('0 0 0'),
[MuzzleParticle] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Items_Weapons_MuzzleParticle] DEFAULT ('default'),
[Animation] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Items_Weapons_Animation] DEFAULT ('assault'),
[BulletID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Items_Weapons_BulletID] DEFAULT ((5.45)),
[Sound_Shot] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Items_Weapons_Sound_Shot] DEFAULT ('Sounds/Weapons/AK74_7_62_Shot'),
[Sound_Reload] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Items_Weapons_Sound_Reload] DEFAULT ('Sounds/Weapons/AK74_Reload'),
[Damage] [float] NOT NULL CONSTRAINT [DF_Items_Weapons_Damage] DEFAULT ((20)),
[isImmediate] [int] NOT NULL CONSTRAINT [DF_Items_Weapons_isImmediate] DEFAULT ((1)),
[Mass] [float] NOT NULL CONSTRAINT [DF_Items_Weapons_Mass] DEFAULT ((0.1)),
[Speed] [float] NOT NULL CONSTRAINT [DF_Items_Weapons_Speed] DEFAULT ((300)),
[DamageDecay] [float] NOT NULL CONSTRAINT [DF_Items_Weapons_DamageDecay] DEFAULT ((0)),
[Area] [float] NOT NULL CONSTRAINT [DF_Items_Weapons_Area] DEFAULT ((0)),
[Delay] [float] NOT NULL CONSTRAINT [DF_Items_Weapons_Delay] DEFAULT ((0)),
[Timeout] [float] NOT NULL CONSTRAINT [DF_Items_Weapons_Timeout] DEFAULT ((0)),
[NumClips] [int] NOT NULL CONSTRAINT [DF_Items_Weapons_NumClips] DEFAULT ((10)),
[Clipsize] [int] NOT NULL CONSTRAINT [DF_Items_Weapons_Clipsize] DEFAULT ((30)),
[ReloadTime] [float] NOT NULL CONSTRAINT [DF_Items_Weapons_Reloadtime] DEFAULT ((2.5)),
[ActiveReloadTick] [float] NOT NULL CONSTRAINT [DF_Items_Weapons_ActiveReloadTick] DEFAULT ((1.2)),
[RateOfFire] [int] NOT NULL CONSTRAINT [DF_Items_Weapons_RateOfFire] DEFAULT ((600)),
[Spread] [float] NOT NULL CONSTRAINT [DF_Items_Weapons_Spread] DEFAULT ((0.08)),
[Recoil] [float] NOT NULL CONSTRAINT [DF_Items_Weapons_Recoil] DEFAULT ((1)),
[NumGrenades] [int] NOT NULL CONSTRAINT [DF_Items_Weapons_NumGrenades] DEFAULT ((0)),
[GrenadeName] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Items_Weapons_GrenadeName] DEFAULT ('asr_grenade'),
[Firemode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Items_Weapons_Firemode] DEFAULT ((101)),
[DetectionRadius] [int] NOT NULL CONSTRAINT [DF_Items_Weapons_DetectionRaius] DEFAULT ((30)),
[ScopeType] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Items_Weapons_ScopeType] DEFAULT ('default'),
[ScopeZoom] [int] NOT NULL CONSTRAINT [DF_Items_Weapons_ScopeZoom] DEFAULT ((0)),
[Price1] [int] NOT NULL CONSTRAINT [DF_Items_Weapons_Price1] DEFAULT ((0)),
[Price7] [int] NOT NULL CONSTRAINT [DF_Items_Weapons_Price7] DEFAULT ((0)),
[Price30] [int] NOT NULL CONSTRAINT [DF_Items_Weapons_Price30] DEFAULT ((0)),
[PriceP] [int] NOT NULL CONSTRAINT [DF_Items_Weapons_PriceP] DEFAULT ((0)),
[IsNew] [int] NOT NULL CONSTRAINT [DF_Items_Weapons_IsNew] DEFAULT ((0)),
[LevelRequired] [int] NOT NULL CONSTRAINT [DF_Items_Weapons_LevelRequired] DEFAULT ((0)),
[GPrice1] [int] NOT NULL CONSTRAINT [DF__Items_Wea__GPric__0EAE1DE1] DEFAULT ((0)),
[GPrice7] [int] NOT NULL CONSTRAINT [DF__Items_Wea__GPric__0FA2421A] DEFAULT ((0)),
[GPrice30] [int] NOT NULL CONSTRAINT [DF__Items_Wea__GPric__10966653] DEFAULT ((0)),
[GPriceP] [int] NOT NULL CONSTRAINT [DF__Items_Wea__GPric__118A8A8C] DEFAULT ((0)),
[ShotsFired] [bigint] NOT NULL CONSTRAINT [DF__Items_Wea__Shots__5BB889C0] DEFAULT ((0)),
[ShotsHits] [bigint] NOT NULL CONSTRAINT [DF__Items_Wea__Shots__5CACADF9] DEFAULT ((0)),
[KillsCQ] [int] NOT NULL CONSTRAINT [DF__Items_Wea__Kills__5DA0D232] DEFAULT ((0)),
[KillsDM] [int] NOT NULL CONSTRAINT [DF__Items_Wea__Kills__5E94F66B] DEFAULT ((0)),
[KillsSB] [int] NOT NULL CONSTRAINT [DF__Items_Wea__Kills__5F891AA4] DEFAULT ((0)),
[IsUpgradeable] [int] NOT NULL CONSTRAINT [DF__Items_Wea__IsUpg__7854C86E] DEFAULT ((1)),
[IsFPS] [int] NOT NULL CONSTRAINT [DF__Items_Wea__IsFPS__270FB757] DEFAULT ((0)),
[FPSSpec0] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSSp__2803DB90] DEFAULT ((0)),
[FPSSpec1] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSSp__28F7FFC9] DEFAULT ((0)),
[FPSSpec2] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSSp__29EC2402] DEFAULT ((0)),
[FPSSpec3] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSSp__2AE0483B] DEFAULT ((0)),
[FPSSpec4] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSSp__2BD46C74] DEFAULT ((0)),
[FPSSpec5] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSSp__2CC890AD] DEFAULT ((0)),
[FPSSpec6] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSSp__2DBCB4E6] DEFAULT ((0)),
[FPSSpec7] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSSp__2EB0D91F] DEFAULT ((0)),
[FPSSpec8] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSSp__2FA4FD58] DEFAULT ((0)),
[FPSAttach0] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSAt__30992191] DEFAULT ((0)),
[FPSAttach1] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSAt__318D45CA] DEFAULT ((0)),
[FPSAttach2] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSAt__32816A03] DEFAULT ((0)),
[FPSAttach3] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSAt__33758E3C] DEFAULT ((0)),
[FPSAttach4] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSAt__3469B275] DEFAULT ((0)),
[FPSAttach5] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSAt__355DD6AE] DEFAULT ((0)),
[FPSAttach6] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSAt__3651FAE7] DEFAULT ((0)),
[FPSAttach7] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSAt__37461F20] DEFAULT ((0)),
[FPSAttach8] [int] NOT NULL CONSTRAINT [DF__Items_Wea__FPSAt__383A4359] DEFAULT ((0)),
[AnimPrefix] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Items_Wea__AnimP__5011CCEA] DEFAULT ('')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Items_Weapons] ADD CONSTRAINT [PK_Items_Weapons] PRIMARY KEY CLUSTERED  ([ItemID]) ON [PRIMARY]
GO
GRANT SELECT ON  [dbo].[Items_Weapons] TO [support1]
GRANT INSERT ON  [dbo].[Items_Weapons] TO [support1]
GRANT DELETE ON  [dbo].[Items_Weapons] TO [support1]
GRANT UPDATE ON  [dbo].[Items_Weapons] TO [support1]
GO
